### PR TITLE
Add Apache 2.0 + MIT combined license

### PR DESCRIPTION
**Pull request by terichadbourne**
- Add combined Apache 2.0 + MIT license in new `LICENSE.md` and link to
it from `README.md`

### CODE REVIEW

**Comment by terichadbourne** [comment]
Hey there. I missed the license in my original repo setup for your chapter and have added it here. Please go ahead and merge this PR to or feel free to reach out with questions or concerns. Thanks!

**Review by alanshaw — APPROVED** [review]
LGTM

**Review by achingbrain — APPROVED** [review]

**Comment by achingbrain** [comment]
Hmm, I can't merge PRs in this repo. @terichadbourne is that intentional?

**Comment by terichadbourne** [comment]
@achingbrain Looks like you haven’t yet accepted your invite to be an admin. If you can’t spot it in your email, let me know and I’ll ping you the link.

**Pull request merged**
